app.name=EstoqueTI Desktop
app.version=1.0.0-SNAPSHOT
app.vendor=Empresa de TI
app.locale=pt-BR
app.session-timeout-minutes=30

database.driver-class-name=org.postgresql.Driver
database.url=jdbc:postgresql://localhost:5432/estoqueti
database.username=estoqueti_app
database.password=
database.schema=estoque_ti
database.hikari.pool-name=EstoqueTIHikariPool
database.hikari.minimum-idle=2
database.hikari.maximum-pool-size=10
database.hikari.connection-timeout-ms=8000
database.hikari.idle-timeout-ms=600000
database.hikari.max-lifetime-ms=1800000
database.hikari.validation-timeout-ms=3000

hibernate.show-sql=false
hibernate.format-sql=true
hibernate.highlight-sql=false
hibernate.hbm2ddl.auto=none
hibernate.jdbc.time-zone=America/Sao_Paulo
hibernate.generate-statistics=false
hibernate.jdbc.batch-size=25

